name: P2P

permissions:
  contents: read
  actions: write

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        job_name:
          - linux-amd64
          - linux-arm64
          - macos-amd64
          - macos-arm64
          - windows-amd64

        include:
          - job_name: linux-amd64
            os: ubuntu-22.04
            path: target/release/libnetsody_p2p.so

          - job_name: linux-arm64
            os: [ self-hosted, linux, ARM64 ]
            path: target/release/libnetsody_p2p.so

          - job_name: macos-amd64
            os: macOS-13
            path: target/release/libnetsody_p2p.dylib

          - job_name: macos-arm64
            os: macOS-latest
            path: target/release/libnetsody_p2p.dylib

          - job_name: windows-amd64
            os: windows-2022
            path: target/release/netsody_p2p.dll

    name: Build netsody-p2p on ${{ matrix.job_name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        if: success() && matrix.job_name == 'linux-arm64'

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build netsody-p2p FFI
        run: cargo build --verbose --package netsody-p2p --features ffi --release

      - name: Upload netsody-p2p artifact
        uses: actions/upload-artifact@v4
        with:
          name: libnetsody-p2p-${{ matrix.job_name }}
          path: ${{ matrix.path }}