name: P2P Super Peer

permissions:
  contents: read
  actions: write

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        job_name:
          - linux-amd64

        include:
          - job_name: linux-amd64
            os: ubuntu-22.04
            path: |
              target/release/netsody-sp

    name: Build netsody-sp on ${{ matrix.job_name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build netsody-sp
        run: cargo build --verbose --package netsody-sp --features prometheus --release

      - name: Upload netsody-sp artifact
        uses: actions/upload-artifact@v4
        with:
          name: netsody-sp-${{ matrix.job_name }}
          path: ${{ matrix.path }}