name: Agent UI

permissions:
  contents: read
  actions: write

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        job_name:
          - linux-amd64
          - macos-amd64
          - macos-arm64
          - windows-amd64

        include:
          - job_name: linux-amd64
            os: ubuntu-22.04
            path: |
              target/release/netsody-ui
              target/release/*.deb

          - job_name: macos-amd64
            os: macOS-13
            path: |
              target/release/netsody-ui
              target/release/*.app
              target/release/*.pkg

          - job_name: macos-arm64
            os: macOS-latest
            path: |
              target/release/netsody-ui
              target/release/*.app
              target/release/*.pkg

          - job_name: windows-amd64
            os: windows-2022
            path: |
              target/release/netsody-ui.exe
              target/release/netsody_*_windows.exe

    name: Build netsody-ui on ${{ matrix.job_name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libpango1.0-dev \
            libxdo-dev \
            libayatana-appindicator3-dev
        if: startsWith(matrix.os, 'ubuntu-')

      - name: Build netsody-ui
        run: cargo build --verbose --package netsody-ui --features dns --release

      - name: Bundle Netsody UI.app
        run: ./netsody-ui/bundle-macos.sh --release
        if: success() && startsWith(matrix.os, 'macOS-')

      - name: Build netsody-agent
        run: cargo build --verbose --package netsody-agent --features dns --release
        if: startsWith(matrix.os, 'macOS-') || startsWith(matrix.os, 'windows-')

      - name: Create macOS Installer
        run: ./netsody-ui/installer-macos.sh --release
        if: success() && startsWith(matrix.os, 'macOS-')

      - name: Bundle netsody-ui.deb
        run: ./netsody-ui/bundle-debian.sh --release
        if: success() && startsWith(matrix.os, 'ubuntu-')

      - name: Create Windows Installer
        uses: joncloud/makensis-action@v5.0
        with:
          script-file: ./netsody-ui/installer-windows.nsi
        if: success() && startsWith(matrix.os, 'windows-')

      - name: Upload netsody-ui artifact(s)
        uses: actions/upload-artifact@v4
        with:
          name: netsody-ui-${{ matrix.job_name }}
          path: ${{ matrix.path }}